ARG version=9 
FROM almalinux:${version}
ARG course=devops
ARG trainer=Abhi
ARG duration=120H
ENV duration=${duration}
RUN echo "course is :${course}", "trainer is :${trainer}","duration is :${duration}"
CMD [ "sleep","100" ]