ARG version=9 
FROM almalinux:${version}
ARG course=devops
ARG trainer=Abhi
ENV duration=120H
RUN echo "course is :${course}", "trainer is :${trainer}","duration is :${duration}"
CMD [ "sleep","100" ]